//! Internal event system for the TUI.
//!
//! Events are generated by the Rust TUI (user input, mouse clicks)
//! and polled by Go via the C FFI boundary.

use serde::{Deserialize, Serialize};

/// Events that flow from Rust TUI → Go.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum TuiEvent {
    /// User pressed Enter in the REPL input.
    UserMessage(String),

    /// User pressed Ctrl+C or Esc.
    Interrupt,

    /// User clicked a navigation item.
    Navigate(String),

    /// User requested to quit the TUI.
    Quit,

    /// User clicked a button or interactive element.
    Action { action: String, data: String },

    /// Window resized.
    Resize { width: u16, height: u16 },

    /// User clicked on a tool badge to expand/collapse.
    ToolToggle { name: String },

    /// Onboarding wizard completed.
    OnboardComplete(String),

    /// Skills configuration completed.
    SkillsComplete(String),
}

impl TuiEvent {
    /// Serialize to JSON for the C FFI boundary.
    pub fn to_json(&self) -> String {
        serde_json::to_string(self).unwrap_or_default()
    }
}
